# Conda environment for okkie.
#
# Install:    conda env create -f environment.yaml
# update:     conda env update -f environment.yaml
# Activate:   conda activate okkie 
# Deactivate: conda deactivate

name: okkie

channels:
  - conda-forge
  - sherpa

dependencies:
  # core dependencies
  - python=3.10
  - pip
  - gammapy>=1.2
  - numpy>1.20
  - regions>=0.5
  - astropy>=6.0
  - scipy!=1.10
  - iminuit>=2.8.0
  - matplotlib>=3.4
  # extra dependencies
  - ipython
  - jupyter
  - jupyterlab
  - naima
  - pandas
  - sherpa
  - healpy
  # dev dependencies
  - ruff
  - tox
  - pre-commit
  - pip:
    - pint-pulsar
