# Conda environment for okkie.
#
# Install:    conda env create -f environment.yaml
# update:     conda env update -f environment.yaml
# Activate:   conda activate okkie
# Deactivate: conda deactivate

name: okkie

channels:
  - conda-forge

dependencies:
  # core dependencies
  - python=3.11
  - pip
  - gammapy>=1.3
  - astropy>=6.0
  - matplotlib>=3.4
  # test dependencies
  - pytest
  # extra dependencies
  - ipython
  - jupyter
  - jupyterlab
  - naima
  - pandas
  - healpy
  # dev dependencies
  - ruff
  - tox
  - pre-commit
  - pip:
    - pint-pulsar
